version: '3'

services:

  users_app:
    container_name: users_app
    build: app
    env_file:
      - .env
    ports:
      - '7000:8000'
    depends_on:
      - users_mongo
    volumes:
      - ./app:/app
      - /var/log/app:/var/log/app

  users_mongo:
    image: mongo
    container_name: user_db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - user_db-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: user_db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

volumes:
  user_db-data:
